config/routes.rb
Timeblocks::Application.routes.draw do
  get "/start(/:id)" => "timeblocks#start", as: "start_activity"
  get "/stop(/:id)" => "timeblocks#stop", as: "stop_activity"
  get "/reset" => "timeblocks#reset", as: "reset_activities"
  resources :activities
  get "/settings" => "pages#settings", as: "settings"
  root :to => "pages#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/activity.rb
class Activity < ActiveRecord::Base

  has_and_belongs_to_many :users
  belongs_to :creator, class_name: "User"
  has_many :timeblocks
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  def active?(user)
    !!user.timeblocks.where(activity_id: self.id, endtime: nil).exists?
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # cancan resource authorization before filter
  # load_and_authorize_resource

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.find_or_create_by_name(activity_params[:name])
    @activity.creator = current_user if @activity.creator_id.blank?

    respond_to do |format|
      if @activity.save
        current_user.activities << @activity unless current_user.activities.include?(@activity)
        format.html { redirect_to root_url, notice: 'Activity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @activity }
      else
        format.html { render action: 'new' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.haml
= simple_form_for(@activity) do |f|
  .row
    = f.error_notification
    .form-group
      = f.input :name, label: false, placeholder: "Activity name", input_html: {class: "form-control input-lg"}
  .row
    = link_to 'Cancel', root_path, class: "btn btn-default col-xs-4"
    = f.button :submit, class: "btn btn-primary col-xs-8"

app/views/activities/edit.html.haml
%h1 Editing activity

= render 'form'

= link_to 'Show', @activity
\|
= link_to 'Back', activities_path

app/views/activities/index.html.haml
%h1 Listing activities

%table
  %tr
    %th Name
    %th Creator
    %th
    %th
    %th

  - @activities.each do |activity|
    %tr
      %td= activity.name
      %td= activity.creator_id
      %td= link_to 'Show', activity
      %td= link_to 'Edit', edit_activity_path(activity)
      %td= link_to 'Destroy', activity, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Activity', new_activity_path

app/views/activities/new.html.haml
%h3{style: "color:#fff;"} Adding a new activity
= render 'form'

app/views/activities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @activity.name
%p
  %b Creator:
  = @activity.creator_id

= link_to 'Edit', edit_activity_path(@activity)
\|
= link_to 'Back', activities_path